type ContactMessage = {
  fullName: string | null;
  email: string;
  message: string;
  metadata?: {
    userAgent?: string;
    referer?: string;
  };
};

function getEnv(key: string): string {
  const value = process.env[key];
  if (!value) return "";
  return value.trim();
}

function parseRecipients(raw: string): string[] {
  return raw
    .split(",")
    .map((entry) => entry.trim())
    .filter(Boolean);
}

function renderHtml(payload: ContactMessage): string {
  const safeName = payload.fullName || "Anonymous";
  const safeEmail = payload.email;
  const safeMessage = payload.message.replace(/\n/g, "<br/>");
  const ua = payload.metadata?.userAgent ? `<p style="margin:0;color:#94a3b8">UA: ${payload.metadata.userAgent}</p>` : "";
  const ref = payload.metadata?.referer ? `<p style="margin:0;color:#94a3b8">Ref: ${payload.metadata.referer}</p>` : "";

  return `<div style="font-family:ui-sans-serif,system-ui">
  <h2 style="margin:0 0 12px;font-size:18px;color:#0f172a">New contact form submission</h2>
  <p style="margin:0 0 8px;color:#1e293b"><strong>Name:</strong> ${safeName}</p>
  <p style="margin:0 0 8px;color:#1e293b"><strong>Email:</strong> ${safeEmail}</p>
  <p style="margin:16px 0 8px;color:#1e293b"><strong>Message:</strong></p>
  <div style="margin:0 0 16px;padding:12px;border-radius:12px;background:#f8fafc;color:#1e293b;line-height:1.5">${safeMessage}</div>
  ${ua}
  ${ref}
  <hr style="margin:20px 0;border:none;border-top:1px solid #e2e8f0"/>
  <p style="margin:0;color:#94a3b8;font-size:12px">Generated by the Neon Shop contact form.</p>
</div>`;
}

async function sendViaPostmark(from: string, to: string[], subject: string, html: string) {
  const token = getEnv("POSTMARK_TOKEN") || getEnv("POSTMARK_SERVER_TOKEN");
  if (!token) throw new Error("POSTMARK_TOKEN is not configured");
  const response = await fetch("https://api.postmarkapp.com/email", {
    method: "POST",
    headers: {
      "X-Postmark-Server-Token": token,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ From: from, To: to.join(","), Subject: subject, HtmlBody: html }),
  });
  if (!response.ok) {
    throw new Error(`postmark ${response.status}: ${await response.text()}`);
  }
}

async function sendViaResend(from: string, to: string[], subject: string, html: string) {
  const token = getEnv("RESEND_API_KEY") || getEnv("RESEND_KEY");
  if (!token) throw new Error("RESEND_API_KEY is not configured");
  const response = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ from, to, subject, html }),
  });
  if (!response.ok) {
    throw new Error(`resend ${response.status}: ${await response.text()}`);
  }
}

export async function sendContactEmail(payload: ContactMessage): Promise<void> {
  const provider = getEnv("CONTACT_NOTIFY_PROVIDER").toLowerCase();
  if (!provider || provider === "none") {
    return;
  }

  const from = getEnv("CONTACT_NOTIFY_FROM") || getEnv("EMAIL_FROM");
  const to = parseRecipients(getEnv("CONTACT_NOTIFY_TO"));
  if (!from || to.length === 0) {
    throw new Error("Contact notify recipients are not configured");
  }

  const subject = `[Contact] ${payload.fullName || payload.email}`;
  const html = renderHtml(payload);

  if (provider === "postmark") {
    await sendViaPostmark(from, to, subject, html);
  } else if (provider === "resend") {
    await sendViaResend(from, to, subject, html);
  } else {
    throw new Error(`Unsupported contact email provider: ${provider}`);
  }
}

