drop extension if exists "pg_net";


  create table "public"."admin_users" (
    "email" text not null
      );


alter table "public"."admin_users" enable row level security;


  create table "public"."admins" (
    "user_id" uuid not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."admins" enable row level security;


  create table "public"."compares" (
    "user_id" uuid not null,
    "offer_id" text not null,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."compares" enable row level security;


  create table "public"."favorites" (
    "user_id" uuid not null,
    "offer_id" text not null,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."favorites" enable row level security;


  create table "public"."private_settings" (
    "key" text not null,
    "value" jsonb not null default '{}'::jsonb,
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."private_settings" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."profiles" enable row level security;


  create table "public"."public_settings" (
    "key" text not null,
    "value" jsonb not null default '{}'::jsonb,
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."public_settings" enable row level security;


  create table "public"."table_name" (
    "id" bigint generated by default as identity not null,
    "inserted_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "updated_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "data" jsonb,
    "name" text
      );


alter table "public"."clicks" drop column "target_host";

alter table "public"."clicks" drop column "target_url";

alter table "public"."clicks" drop column "target_url_final";

alter table "public"."clicks" add column "created_at" timestamp with time zone default now();

--alter table "public"."clicks" alter column "id" set default gen_random_uuid();

alter table "public"."clicks" alter column "id" drop identity;

--alter table "public"."clicks" alter column "id" set data type uuid using "id"::uuid;

alter table "public"."clicks" alter column "params" set default '{}'::jsonb;

alter table "public"."clicks" alter column "params" set not null;

alter table "public"."clicks" alter column "slug" set not null;

alter table "public"."offers" drop column "created_at";

alter table "public"."offers" drop column "updated_at";

alter table "public"."offers" alter column "license" drop default;

alter table "public"."offers" alter column "methods" set not null;

alter table "public"."offers" alter column "payout" set default ''::text;

alter table "public"."offers" alter column "payout" set not null;

alter table "public"."offers" alter column "rating" set default 0;

alter table "public"."offers" alter column "rating" set not null;

alter table "public"."partner_offers" add column "updated_at" timestamp with time zone not null default now();

alter table "public"."partners" add column "updated_at" timestamp with time zone not null default now();

alter table "public"."webhook_logs" add column "event_type" text generated always as (type) stored;

alter table "public"."webhook_logs" alter column "payload" set default '{}'::jsonb;

CREATE UNIQUE INDEX admin_users_pkey ON public.admin_users USING btree (email);

CREATE UNIQUE INDEX admins_pkey ON public.admins USING btree (user_id);

CREATE UNIQUE INDEX compares_pkey ON public.compares USING btree (user_id, offer_id);

CREATE UNIQUE INDEX favorites_pkey ON public.favorites USING btree (user_id, offer_id);

CREATE INDEX idx_admin_users_email_lower ON public.admin_users USING btree (lower(email));

CREATE INDEX idx_compares_user_created_at ON public.compares USING btree (user_id, created_at DESC);

CREATE INDEX idx_favorites_user_created_at ON public.favorites USING btree (user_id, created_at DESC);

CREATE INDEX idx_offers_enabled_position ON public.offers USING btree ("position") WHERE (enabled = true);

CREATE INDEX idx_offers_methods_gin ON public.offers USING gin (methods);

CREATE INDEX partner_offers_offer_slug_idx ON public.partner_offers USING btree (offer_slug);

CREATE INDEX partner_offers_pinned_idx ON public.partner_offers USING btree (pinned) WHERE (pinned = true);

CREATE INDEX partner_offers_pinned_partner_idx ON public.partner_offers USING btree (partner_id) WHERE (pinned = true);

CREATE INDEX partners_expires_at_idx ON public.partners USING btree (expires_at);

CREATE INDEX partners_expires_at_null_idx ON public.partners USING btree (expires_at) WHERE (expires_at IS NULL);

CREATE INDEX partners_expires_idx ON public.partners USING btree (expires_at);

CREATE UNIQUE INDEX partners_name_uidx ON public.partners USING btree (lower(name));

CREATE UNIQUE INDEX private_settings_pkey ON public.private_settings USING btree (key);

CREATE INDEX private_settings_updated_idx ON public.private_settings USING btree (updated_at DESC);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX public_settings_pkey ON public.public_settings USING btree (key);

CREATE INDEX public_settings_updated_idx ON public.public_settings USING btree (updated_at DESC);

CREATE UNIQUE INDEX table_name_pkey ON public.table_name USING btree (id);

CREATE INDEX webhook_logs_created_idx ON public.webhook_logs USING btree (created_at DESC);

CREATE INDEX webhook_logs_type_idx ON public.webhook_logs USING btree (type);

alter table "public"."admin_users" add constraint "admin_users_pkey" PRIMARY KEY using index "admin_users_pkey";

alter table "public"."admins" add constraint "admins_pkey" PRIMARY KEY using index "admins_pkey";

alter table "public"."compares" add constraint "compares_pkey" PRIMARY KEY using index "compares_pkey";

alter table "public"."favorites" add constraint "favorites_pkey" PRIMARY KEY using index "favorites_pkey";

alter table "public"."private_settings" add constraint "private_settings_pkey" PRIMARY KEY using index "private_settings_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."public_settings" add constraint "public_settings_pkey" PRIMARY KEY using index "public_settings_pkey";

alter table "public"."table_name" add constraint "table_name_pkey" PRIMARY KEY using index "table_name_pkey";

alter table "public"."compares" add constraint "compares_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."compares" validate constraint "compares_user_id_fkey";

alter table "public"."favorites" add constraint "favorites_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."favorites" validate constraint "favorites_user_id_fkey";

alter table "public"."offers" add constraint "offers_license_check" CHECK ((license = ANY (ARRAY['MGA'::text, 'UKGC'::text, 'Curaçao'::text, 'Other'::text]))) not valid;

alter table "public"."offers" validate constraint "offers_license_check";

alter table "public"."partners" add constraint "partners_email_chk" CHECK (((email IS NULL) OR (email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'::text))) not valid;

alter table "public"."partners" validate constraint "partners_email_chk";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.profiles (id)
  values (new.id)
  on conflict (id) do nothing;
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.is_admin()
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists(
    select 1
    from public.admin_users a
    where lower(a.email) = lower(coalesce(auth.jwt()->>'email',''))
  );
$function$
;

create or replace view "public"."my_compares" as  SELECT offer_id,
    created_at
   FROM compares
  WHERE (user_id = auth.uid());


create or replace view "public"."my_favorites" as  SELECT offer_id,
    created_at
   FROM favorites
  WHERE (user_id = auth.uid());


CREATE OR REPLACE FUNCTION public.set_setting(k text, v jsonb, is_private boolean DEFAULT false)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if is_private then
    insert into public.private_settings(key, value) values (k, v)
    on conflict (key) do update set value = excluded.value;
  else
    insert into public.public_settings(key, value) values (k, v)
    on conflict (key) do update set value = excluded.value;
  end if;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.touch_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end $function$
;

create or replace view "public"."v_pinned_offer_slugs" as  SELECT DISTINCT po.offer_slug
   FROM (partner_offers po
     JOIN partners p ON ((p.id = po.partner_id)))
  WHERE ((po.pinned = true) AND ((p.expires_at IS NULL) OR (p.expires_at > now())));


grant delete on table "public"."admin_users" to "anon";

grant insert on table "public"."admin_users" to "anon";

grant references on table "public"."admin_users" to "anon";

grant select on table "public"."admin_users" to "anon";

grant trigger on table "public"."admin_users" to "anon";

grant truncate on table "public"."admin_users" to "anon";

grant update on table "public"."admin_users" to "anon";

grant delete on table "public"."admin_users" to "authenticated";

grant insert on table "public"."admin_users" to "authenticated";

grant references on table "public"."admin_users" to "authenticated";

grant select on table "public"."admin_users" to "authenticated";

grant trigger on table "public"."admin_users" to "authenticated";

grant truncate on table "public"."admin_users" to "authenticated";

grant update on table "public"."admin_users" to "authenticated";

grant delete on table "public"."admin_users" to "service_role";

grant insert on table "public"."admin_users" to "service_role";

grant references on table "public"."admin_users" to "service_role";

grant select on table "public"."admin_users" to "service_role";

grant trigger on table "public"."admin_users" to "service_role";

grant truncate on table "public"."admin_users" to "service_role";

grant update on table "public"."admin_users" to "service_role";

grant delete on table "public"."admins" to "anon";

grant insert on table "public"."admins" to "anon";

grant references on table "public"."admins" to "anon";

grant select on table "public"."admins" to "anon";

grant trigger on table "public"."admins" to "anon";

grant truncate on table "public"."admins" to "anon";

grant update on table "public"."admins" to "anon";

grant delete on table "public"."admins" to "authenticated";

grant insert on table "public"."admins" to "authenticated";

grant references on table "public"."admins" to "authenticated";

grant select on table "public"."admins" to "authenticated";

grant trigger on table "public"."admins" to "authenticated";

grant truncate on table "public"."admins" to "authenticated";

grant update on table "public"."admins" to "authenticated";

grant delete on table "public"."admins" to "service_role";

grant insert on table "public"."admins" to "service_role";

grant references on table "public"."admins" to "service_role";

grant select on table "public"."admins" to "service_role";

grant trigger on table "public"."admins" to "service_role";

grant truncate on table "public"."admins" to "service_role";

grant update on table "public"."admins" to "service_role";

grant delete on table "public"."compares" to "anon";

grant insert on table "public"."compares" to "anon";

grant references on table "public"."compares" to "anon";

grant select on table "public"."compares" to "anon";

grant trigger on table "public"."compares" to "anon";

grant truncate on table "public"."compares" to "anon";

grant update on table "public"."compares" to "anon";

grant delete on table "public"."compares" to "authenticated";

grant insert on table "public"."compares" to "authenticated";

grant references on table "public"."compares" to "authenticated";

grant select on table "public"."compares" to "authenticated";

grant trigger on table "public"."compares" to "authenticated";

grant truncate on table "public"."compares" to "authenticated";

grant update on table "public"."compares" to "authenticated";

grant delete on table "public"."compares" to "service_role";

grant insert on table "public"."compares" to "service_role";

grant references on table "public"."compares" to "service_role";

grant select on table "public"."compares" to "service_role";

grant trigger on table "public"."compares" to "service_role";

grant truncate on table "public"."compares" to "service_role";

grant update on table "public"."compares" to "service_role";

grant delete on table "public"."favorites" to "anon";

grant insert on table "public"."favorites" to "anon";

grant references on table "public"."favorites" to "anon";

grant select on table "public"."favorites" to "anon";

grant trigger on table "public"."favorites" to "anon";

grant truncate on table "public"."favorites" to "anon";

grant update on table "public"."favorites" to "anon";

grant delete on table "public"."favorites" to "authenticated";

grant insert on table "public"."favorites" to "authenticated";

grant references on table "public"."favorites" to "authenticated";

grant select on table "public"."favorites" to "authenticated";

grant trigger on table "public"."favorites" to "authenticated";

grant truncate on table "public"."favorites" to "authenticated";

grant update on table "public"."favorites" to "authenticated";

grant delete on table "public"."favorites" to "service_role";

grant insert on table "public"."favorites" to "service_role";

grant references on table "public"."favorites" to "service_role";

grant select on table "public"."favorites" to "service_role";

grant trigger on table "public"."favorites" to "service_role";

grant truncate on table "public"."favorites" to "service_role";

grant update on table "public"."favorites" to "service_role";

grant delete on table "public"."private_settings" to "anon";

grant insert on table "public"."private_settings" to "anon";

grant references on table "public"."private_settings" to "anon";

grant select on table "public"."private_settings" to "anon";

grant trigger on table "public"."private_settings" to "anon";

grant truncate on table "public"."private_settings" to "anon";

grant update on table "public"."private_settings" to "anon";

grant delete on table "public"."private_settings" to "authenticated";

grant insert on table "public"."private_settings" to "authenticated";

grant references on table "public"."private_settings" to "authenticated";

grant select on table "public"."private_settings" to "authenticated";

grant trigger on table "public"."private_settings" to "authenticated";

grant truncate on table "public"."private_settings" to "authenticated";

grant update on table "public"."private_settings" to "authenticated";

grant delete on table "public"."private_settings" to "service_role";

grant insert on table "public"."private_settings" to "service_role";

grant references on table "public"."private_settings" to "service_role";

grant select on table "public"."private_settings" to "service_role";

grant trigger on table "public"."private_settings" to "service_role";

grant truncate on table "public"."private_settings" to "service_role";

grant update on table "public"."private_settings" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."public_settings" to "anon";

grant insert on table "public"."public_settings" to "anon";

grant references on table "public"."public_settings" to "anon";

grant select on table "public"."public_settings" to "anon";

grant trigger on table "public"."public_settings" to "anon";

grant truncate on table "public"."public_settings" to "anon";

grant update on table "public"."public_settings" to "anon";

grant delete on table "public"."public_settings" to "authenticated";

grant insert on table "public"."public_settings" to "authenticated";

grant references on table "public"."public_settings" to "authenticated";

grant select on table "public"."public_settings" to "authenticated";

grant trigger on table "public"."public_settings" to "authenticated";

grant truncate on table "public"."public_settings" to "authenticated";

grant update on table "public"."public_settings" to "authenticated";

grant delete on table "public"."public_settings" to "service_role";

grant insert on table "public"."public_settings" to "service_role";

grant references on table "public"."public_settings" to "service_role";

grant select on table "public"."public_settings" to "service_role";

grant trigger on table "public"."public_settings" to "service_role";

grant truncate on table "public"."public_settings" to "service_role";

grant update on table "public"."public_settings" to "service_role";

grant delete on table "public"."table_name" to "anon";

grant insert on table "public"."table_name" to "anon";

grant references on table "public"."table_name" to "anon";

grant select on table "public"."table_name" to "anon";

grant trigger on table "public"."table_name" to "anon";

grant truncate on table "public"."table_name" to "anon";

grant update on table "public"."table_name" to "anon";

grant delete on table "public"."table_name" to "authenticated";

grant insert on table "public"."table_name" to "authenticated";

grant references on table "public"."table_name" to "authenticated";

grant select on table "public"."table_name" to "authenticated";

grant trigger on table "public"."table_name" to "authenticated";

grant truncate on table "public"."table_name" to "authenticated";

grant update on table "public"."table_name" to "authenticated";

grant delete on table "public"."table_name" to "service_role";

grant insert on table "public"."table_name" to "service_role";

grant references on table "public"."table_name" to "service_role";

grant select on table "public"."table_name" to "service_role";

grant trigger on table "public"."table_name" to "service_role";

grant truncate on table "public"."table_name" to "service_role";

grant update on table "public"."table_name" to "service_role";


  create policy "admin_users select own"
  on "public"."admin_users"
  as permissive
  for select
  to authenticated
using ((lower(email) = lower(COALESCE((auth.jwt() ->> 'email'::text), ''::text))));



  create policy "allow insert for anon"
  on "public"."clicks"
  as permissive
  for insert
  to anon
with check (true);



  create policy "compares delete own"
  on "public"."compares"
  as permissive
  for delete
  to public
using ((auth.uid() = user_id));



  create policy "compares delete"
  on "public"."compares"
  as permissive
  for delete
  to public
using ((auth.uid() = user_id));



  create policy "compares insert own"
  on "public"."compares"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "compares insert"
  on "public"."compares"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "compares read"
  on "public"."compares"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "compares select own"
  on "public"."compares"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "favorites delete own"
  on "public"."favorites"
  as permissive
  for delete
  to public
using ((auth.uid() = user_id));



  create policy "favorites delete"
  on "public"."favorites"
  as permissive
  for delete
  to public
using ((auth.uid() = user_id));



  create policy "favorites insert own"
  on "public"."favorites"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "favorites insert"
  on "public"."favorites"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "favorites read"
  on "public"."favorites"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "favorites select own"
  on "public"."favorites"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "offers_read_public"
  on "public"."offers"
  as permissive
  for select
  to public
using (true);



  create policy "offers_write_admins_only"
  on "public"."offers"
  as permissive
  for all
  to authenticated
using ((EXISTS ( SELECT 1
   FROM admin_users a
  WHERE (a.email = (auth.jwt() ->> 'email'::text)))))
with check ((EXISTS ( SELECT 1
   FROM admin_users a
  WHERE (a.email = (auth.jwt() ->> 'email'::text)))));



  create policy "admin manage partner_offers"
  on "public"."partner_offers"
  as permissive
  for all
  to authenticated
using ((((auth.jwt() -> 'user_metadata'::text) ->> 'role'::text) = 'admin'::text))
with check ((((auth.jwt() -> 'user_metadata'::text) ->> 'role'::text) = 'admin'::text));



  create policy "admins manage partner_offers"
  on "public"."partner_offers"
  as permissive
  for all
  to authenticated
using ((EXISTS ( SELECT 1
   FROM admins a
  WHERE (a.user_id = auth.uid()))))
with check ((EXISTS ( SELECT 1
   FROM admins a
  WHERE (a.user_id = auth.uid()))));



  create policy "admins manage partners"
  on "public"."partners"
  as permissive
  for all
  to authenticated
using ((EXISTS ( SELECT 1
   FROM admins a
  WHERE (a.user_id = auth.uid()))))
with check ((EXISTS ( SELECT 1
   FROM admins a
  WHERE (a.user_id = auth.uid()))));



  create policy "auth read private settings"
  on "public"."private_settings"
  as permissive
  for select
  to authenticated
using (true);



  create policy "auth write private settings"
  on "public"."private_settings"
  as permissive
  for all
  to authenticated
using (true)
with check (true);



  create policy "profiles insert self"
  on "public"."profiles"
  as permissive
  for insert
  to public
with check ((auth.uid() = id));



  create policy "profiles select own"
  on "public"."profiles"
  as permissive
  for select
  to public
using ((auth.uid() = id));



  create policy "profiles self"
  on "public"."profiles"
  as permissive
  for select
  to public
using ((auth.uid() = id));



  create policy "profiles update own"
  on "public"."profiles"
  as permissive
  for update
  to public
using ((auth.uid() = id))
with check ((auth.uid() = id));



  create policy "anon read public settings"
  on "public"."public_settings"
  as permissive
  for select
  to anon
using (true);



  create policy "auth write public settings"
  on "public"."public_settings"
  as permissive
  for all
  to authenticated
using (true)
with check (true);



  create policy "admin read webhook_logs"
  on "public"."webhook_logs"
  as permissive
  for select
  to authenticated
using (COALESCE((((auth.jwt() -> 'user_metadata'::text) ->> 'role'::text) = 'admin'::text), false));



  create policy "auth can insert webhook_logs"
  on "public"."webhook_logs"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "auth can read webhook_logs"
  on "public"."webhook_logs"
  as permissive
  for select
  to authenticated
using (true);



  create policy "auth read webhook_logs"
  on "public"."webhook_logs"
  as permissive
  for select
  to authenticated
using (true);


CREATE TRIGGER trg_partner_offers_updated_at BEFORE UPDATE ON public.partner_offers FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TRIGGER trg_partners_updated_at BEFORE UPDATE ON public.partners FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TRIGGER trg_private_settings_updated_at BEFORE UPDATE ON public.private_settings FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TRIGGER trg_public_settings_updated_at BEFORE UPDATE ON public.public_settings FOR EACH ROW EXECUTE FUNCTION touch_updated_at();


