-- Migration from supabase/clicks.sql
-- supabase/clicks.sql
-- Minimal logging table for outbound affiliate clicks via /go/:slug

create table if not exists public.clicks (
  id                bigint generated by default as identity primary key,
  ts                timestamptz not null default now(),
  slug              text,
  click_id          text,
  target_url        text,
  target_url_final  text,
  target_host       text,
  params            jsonb,
  referrer          text,
  user_agent        text
);

-- Helpful indexes
create index if not exists clicks_ts_idx on public.clicks (ts desc);
do $$ begin
  if exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='clicks' and column_name='slug'
  ) then
    if not exists (
      select 1 from pg_indexes where schemaname='public' and tablename='clicks' and indexname='clicks_slug_ts_idx'
    ) then
      execute 'create index clicks_slug_ts_idx on public.clicks (slug, ts desc)';
    end if;
  end if;
end $$;
create index if not exists clicks_click_id_idx on public.clicks (click_id);


