-- Migration: v2 schema for affiliate site
-- Goal: normalized offers, clicks, impressions with FK and sane RLS
-- Idempotent: safe to run multiple times

-- 0) Helpers ---------------------------------------------------------------
create extension if not exists pgcrypto;

-- 1) offers ----------------------------------------------------------------
create table if not exists public.offers (
  id            bigint generated by default as identity primary key,
  slug          text unique not null,
  name          text not null,
  link          text not null,
  enabled       boolean not null default true,
  methods       text[] not null default '{}'::text[],
  rating        numeric(2,1),
  payout        text,
  payout_hours  text,
  license       text,
  position      int not null default 0,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- reconcile columns (id / timestamps first to avoid trigger issues)
alter table public.offers add column if not exists id bigint;
alter table public.offers add column if not exists created_at timestamptz default now();
alter table public.offers add column if not exists updated_at timestamptz default now();

-- ensure id has default/identity
do $$
begin
  if (select pg_get_expr(adbin, adrelid)
      from pg_attrdef d
      join pg_attribute a on a.attrelid=d.adrelid and a.attnum=d.adnum
      join pg_class t on t.oid=d.adrelid
      where t.relname='offers' and a.attname='id') is null then
    execute 'create sequence if not exists public.offers_id_seq';
    execute 'alter table public.offers alter column id set default nextval(''public.offers_id_seq'')';
  end if;

  execute 'update public.offers set id = nextval(''public.offers_id_seq'') where id is null';

  begin
    execute 'alter table public.offers alter column id set not null';
  exception when others then null;
  end;
end $$;

-- ensure slug is present/unique
alter table public.offers add column if not exists slug text;
alter table public.offers alter column slug set not null;
create unique index if not exists idx_offers_slug_unique on public.offers(slug);
do $$
begin
  if not exists (
    select 1 from information_schema.table_constraints
    where table_schema='public' and table_name='offers'
      and constraint_type='UNIQUE' and constraint_name='offers_slug_key'
  ) then
    if exists (
      select 1 from pg_indexes where schemaname='public' and tablename='offers' and indexname='idx_offers_slug_unique'
    ) then
      execute 'alter table public.offers add constraint offers_slug_key unique using index idx_offers_slug_unique';
    else
      execute 'alter table public.offers add constraint offers_slug_key unique (slug)';
    end if;
  end if;
end $$;

-- other offer columns: be tolerant to existing shapes
alter table public.offers add column if not exists name text;
alter table public.offers alter column name set not null;

alter table public.offers add column if not exists link text;
do $$
begin
  update public.offers set link = 'https://example.com' where link is null;
  begin
    execute 'alter table public.offers alter column link set not null';
  exception when others then null;
  end;
end $$;

alter table public.offers add column if not exists enabled boolean;
alter table public.offers alter column enabled set default true;
alter table public.offers alter column enabled set not null;

alter table public.offers add column if not exists methods text[];
alter table public.offers alter column methods set default '{}'::text[];
alter table public.offers alter column methods set not null;

alter table public.offers add column if not exists rating numeric(2,1);
do $$
begin
  perform 1
  from information_schema.columns
  where table_schema='public' and table_name='offers' and column_name='rating'
    and data_type='numeric' and (numeric_precision, numeric_scale) is distinct from (2,1);
  if found then
    begin
      execute 'alter table public.offers alter column rating type numeric(2,1) using round(coalesce(rating,0)::numeric,1)';
    exception when others then null;
    end;
  end if;
end $$;

alter table public.offers add column if not exists payout text;

do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='offers' and column_name='payout_hours'
  ) then
    execute 'alter table public.offers add column payout_hours text';
  else
    if exists (
      select 1 from information_schema.columns
      where table_schema='public' and table_name='offers' and column_name='payout_hours' and data_type<>'text'
    ) then
      begin
        execute 'alter table public.offers alter column payout_hours type text using payout_hours::text';
      exception when others then null;
      end;
    end if;
  end if;
end $$;

alter table public.offers add column if not exists license text;
do $$
begin
  begin
    execute 'alter table public.offers alter column license set default ''Other''';
  exception when others then null;
  end;
end $$;

alter table public.offers add column if not exists position int;
update public.offers set position = 0 where position is null;
alter table public.offers alter column position set default 0;
alter table public.offers alter column position set not null;

alter table public.offers add column if not exists created_at timestamptz default now();
alter table public.offers add column if not exists updated_at timestamptz default now();

-- updated_at trigger
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists trg_offers_updated_at on public.offers;
create trigger trg_offers_updated_at
before update on public.offers
for each row execute function public.set_updated_at();

-- ⚠️ LEGACY FK partner_offers.offer_slug -> offers.slug
-- Только если колонка offer_slug СУЩЕСТВУЕТ. Иначе — пропускаем.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='partner_offers' and column_name='offer_slug'
  ) then
    -- убрать старый FK, если висит с другим именем/формой
    if exists (
      select 1 from information_schema.table_constraints
      where constraint_schema='public'
        and table_name='partner_offers'
        and constraint_name='partner_offers_offer_slug_fkey'
        and constraint_type='FOREIGN KEY'
    ) then
      execute 'alter table public.partner_offers drop constraint partner_offers_offer_slug_fkey';
    end if;

    -- повесить нужный FK, если ещё нет
    if not exists (
      select 1
      from information_schema.table_constraints tc
      join information_schema.key_column_usage kcu
        on kcu.constraint_name = tc.constraint_name and kcu.constraint_schema = tc.constraint_schema
      where tc.table_schema='public'
        and tc.table_name='partner_offers'
        and tc.constraint_type='FOREIGN KEY'
        and kcu.column_name='offer_slug'
    ) then
      execute $x$
        alter table public.partner_offers
          add constraint partner_offers_offer_slug_fkey
          foreign key (offer_slug) references public.offers(slug)
          on delete cascade
      $x$;
    end if;
  else
    raise notice 'partner_offers.offer_slug absent; skipping legacy FK to offers.slug';
  end if;
end $$;

-- RLS for offers
alter table public.offers enable row level security;

drop policy if exists "Public read enabled offers" on public.offers;
drop policy if exists "Auth read all offers" on public.offers;
drop policy if exists "Auth write offers" on public.offers;
drop policy if exists "offers_anon_select" on public.offers;
drop policy if exists "offers_auth_select" on public.offers;
drop policy if exists "offers_write_service" on public.offers;

create policy "offers_anon_select"
  on public.offers for select
  to anon
  using (true);

create policy "offers_auth_select"
  on public.offers for select
  to authenticated
  using (true);

create policy "offers_write_service"
  on public.offers for all
  to service_role
  using (true)
  with check (true);

-- 2) clicks ----------------------------------------------------------------
create table if not exists public.clicks (
  id         bigint generated by default as identity primary key,
  ts         timestamptz not null default now(),
  offer_id   bigint,
  click_id   text,
  params     jsonb not null default '{}'::jsonb,
  referrer   text,
  user_agent text,
  ip_hash    text
);

alter table public.clicks add column if not exists ts timestamptz default now();
alter table public.clicks add column if not exists offer_id bigint;
alter table public.clicks add column if not exists click_id text;
alter table public.clicks add column if not exists params jsonb;
alter table public.clicks alter column params set default '{}'::jsonb;
alter table public.clicks alter column params set not null;
alter table public.clicks add column if not exists referrer text;
alter table public.clicks add column if not exists user_agent text;
alter table public.clicks add column if not exists ip_hash text;

-- ensure clicks.id has default/identity
do $$
begin
  if (select pg_get_expr(d.adbin, d.adrelid)
      from pg_attrdef d
      join pg_attribute a on a.attrelid=d.adrelid and a.attnum=d.adnum
      join pg_class t on t.oid=d.adrelid
      where t.relname='clicks' and a.attname='id') is null
     and not exists (
       select 1 from information_schema.columns
       where table_schema='public' and table_name='clicks' and column_name='id' and is_identity='YES'
     ) then
    begin
      execute 'alter table public.clicks alter column id add generated by default as identity';
    exception when others then
      execute 'create sequence if not exists public.clicks_id_seq';
      execute 'alter table public.clicks alter column id set default nextval(''public.clicks_id_seq'')';
    end;
  end if;
end $$;

-- backfill offer_id from legacy slug if present
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='clicks' and column_name='slug'
  ) then
    execute 'update public.clicks c
             set offer_id = o.id
             from public.offers o
             where c.offer_id is null and o.slug = c.slug';
  end if;
end $$;

-- ensure placeholder
insert into public.offers (slug, name, link, enabled, methods, license)
values ('unknown','Unknown Offer','https://example.com', true, '{}'::text[], 'Other')
on conflict (slug) do nothing;

do $$
declare u_id bigint;
begin
  select id into u_id from public.offers where slug = 'unknown';

  update public.impressions
  set offer_id = u_id
  where offer_id is null;

  update public.clicks
  set offer_id = u_id
  where offer_id is null;
end $$;

-- FK clicks.offer_id -> offers.id
do $$
begin
  if not exists (
    select 1 from information_schema.table_constraints tc
    join information_schema.key_column_usage kcu using (constraint_name, constraint_schema)
    where tc.table_schema='public' and tc.table_name='clicks'
      and tc.constraint_type='FOREIGN KEY' and kcu.column_name='offer_id'
  ) then
    execute 'alter table public.clicks
             add constraint clicks_offer_id_fkey
             foreign key (offer_id) references public.offers(id)
             on delete cascade';
  end if;
end $$;

-- drop legacy columns
alter table public.clicks drop column if exists slug;
alter table public.clicks drop column if exists target_url;
alter table public.clicks drop column if exists target_url_final;
alter table public.clicks drop column if exists target_host;

-- make offer_id required
begin;
  alter table public.clicks alter column offer_id set not null;
commit;

-- indexes
create index if not exists idx_clicks_offer_ts on public.clicks (offer_id, ts desc);
create index if not exists idx_clicks_ip_ts    on public.clicks (ip_hash, ts desc);

-- RLS
alter table public.clicks enable row level security;
drop policy if exists "auth can read clicks" on public.clicks;
drop policy if exists "clicks_select_authenticated" on public.clicks;
drop policy if exists "clicks_insert_service" on public.clicks;

create policy "clicks_select_authenticated"
  on public.clicks for select
  to authenticated
  using (true);

create policy "clicks_insert_service"
  on public.clicks for insert
  to service_role
  with check (true);

-- 3) impressions -----------------------------------------------------------
create table if not exists public.impressions (
  id         bigint generated by default as identity primary key,
  ts         timestamptz not null default now(),
  offer_id   bigint not null,
  referrer   text,
  user_agent text,
  ip_hash    text
);

alter table public.impressions add column if not exists ts timestamptz default now();
alter table public.impressions add column if not exists offer_id bigint;
alter table public.impressions add column if not exists referrer text;
alter table public.impressions add column if not exists user_agent text;
alter table public.impressions add column if not exists ip_hash text;

-- backfill from legacy slug
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='impressions' and column_name='slug'
  ) then
    execute 'update public.impressions i
             set offer_id = o.id
             from public.offers o
             where i.offer_id is null and o.slug = i.slug';
  end if;
end $$;

-- ensure placeholder
-- разок создаём плейсхолдер (если ещё нет)
insert into public.offers (slug, name, link, enabled, methods, license)
values ('unknown','Unknown Offer','https://example.com', true, '{}'::text[], 'Other')
on conflict (slug) do nothing;

-- правки апдейтов
update public.impressions
set offer_id = (select id from public.offers where slug='unknown')
where offer_id is null;

update public.clicks
set offer_id = (select id from public.offers where slug='unknown')
where offer_id is null;

-- drop legacy columns
alter table public.impressions drop column if exists slug;
alter table public.impressions drop column if exists device;

-- rename referer -> referrer if needed
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='impressions' and column_name='referer'
  ) and not exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='impressions' and column_name='referrer'
  ) then
    execute 'alter table public.impressions rename column referer to referrer';
  end if;
end $$;

-- ensure id type
do $$
declare coltype text;
declare pk_name text;
begin
  select data_type into coltype
  from information_schema.columns
  where table_schema='public' and table_name='impressions' and column_name='id';

  if coltype = 'uuid' then
    select c.conname into pk_name
    from pg_constraint c
    join pg_class t on t.oid=c.conrelid
    where t.relname='impressions' and c.contype='p';
    if pk_name is not null then
      execute format('alter table public.impressions drop constraint %I', pk_name);
    end if;
    execute 'alter table public.impressions drop column id';
    execute 'alter table public.impressions add column id bigint generated by default as identity primary key';
  end if;
end $$;

-- FK impressions.offer_id -> offers.id
do $$
begin
  if not exists (
    select 1 from information_schema.table_constraints tc
    join information_schema.key_column_usage kcu using (constraint_name, constraint_schema)
    where tc.table_schema='public' and tc.table_name='impressions'
      and tc.constraint_type='FOREIGN KEY' and kcu.column_name='offer_id'
  ) then
    execute 'alter table public.impressions
             add constraint impressions_offer_id_fkey
             foreign key (offer_id) references public.offers(id)
             on delete cascade';
  end if;
end $$;

-- make offer_id required
begin;
  alter table public.impressions alter column offer_id set not null;
commit;

-- indexes
create index if not exists idx_impressions_offer_ts on public.impressions (offer_id, ts desc);

-- RLS
alter table public.impressions enable row level security;
drop policy if exists "auth read impressions" on public.impressions;
drop policy if exists "impressions_select_authenticated" on public.impressions;
drop policy if exists "impressions_insert_service" on public.impressions;

create policy "impressions_select_authenticated"
  on public.impressions for select
  to authenticated
  using (true);

create policy "impressions_insert_service"
  on public.impressions for insert
  to service_role
  with check (true);

-- 4) acceptance sanity -----------------------------------------------------
create index if not exists idx_offers_enabled  on public.offers(enabled);
create index if not exists idx_offers_position on public.offers(position);