-- Migration from supabase/clicks.sql
-- supabase/clicks.sql
-- Minimal logging table for outbound affiliate clicks via /go/:slug

create table if not exists public.clicks (
  id                bigint generated by default as identity primary key,
  ts                timestamptz not null default now(),
  slug              text,
  click_id          text,
  target_url        text,
  target_url_final  text,
  target_host       text,
  params            jsonb,
  referrer          text,
  user_agent        text
);

-- Helpful indexes
create index if not exists clicks_ts_idx on public.clicks (ts desc);
create index if not exists clicks_slug_ts_idx on public.clicks (slug, ts desc);
create index if not exists clicks_click_id_idx on public.clicks (click_id);


